### ISSUE TITLE
Tags selector menu for blog posts not working

### ISSUE THREAD

**Issue by JonathanPeterRajan** [reflexjs/reflex#30] opened 2020-08-04 10:58 UTC
![Screenshot_2020-08-04 Reflex Reflex](https://user-images.githubusercontent.com/62900297/89286065-77421e80-d649-11ea-8bbc-d757c7aec384.png)
![Screenshot_2020-08-04 Reflex Reflex(1)](https://user-images.githubusercontent.com/62900297/89286069-790be200-d649-11ea-9253-28b17a8499e9.png)
As shown from the images, after you click on a tag, it directs you to another page. In that none of the posts with that tag are showing.

**Comment by arshad** [comment] 2020-08-04 10:59
Can you try a `gatsby clean && gatsby develop` please?

**Comment by JonathanPeterRajan** [comment] 2020-08-04 11:16
The problem still persists

**Comment by arshad** [comment] 2020-08-04 18:04
Hmm, kinda hard to debug this without seeing the code but let's try a few things.

Can you paste in the frontmatter for one of the posts please?

**Comment by JonathanPeterRajan** [comment] 2020-08-04 18:44
the mdx file for the post is :
---
title: Tit
excerpt: A short description for this post.
date: 2020-07-08
image: cover-image-for-post.jpg
caption: Caption for the cover image
published: true
featured: true
author: 
tags:
  - Writing
  - Life
  - Technology
---

Post content goes here.
<Button>Technology</Button>

**Comment by JonathanPeterRajan** [comment] 2020-08-04 18:45
The code for the tag button selector (which you made for me):
import { useStaticQuery, graphql } from "gatsby"

export const usePostTag = () => {
  const data = useStaticQuery(graphql`
    query {
      # Find all post tags, return the name and slug fields.
      allPostTag {
        nodes {
          name
          slug
        }
      }
      # Find all posts grouped by the tag slug and return the total count.
      allPost {
        group(field: tags___slug) {
          slug: fieldValue
          totalCount
        }
      }
    }
  `)

  // Loop through the post tags and add the count by matching slugs.
  data.allPostTag.nodes.map(
    (node) =>
      (node.count = data.allPost.group.filter(
        ({ slug }) => slug === node.slug
      )[0].totalCount)
  )

  return data.allPostTag.nodes
}

**Comment by JonathanPeterRajan** [comment] 2020-08-17 16:20
Hi, I tried to use the source code for the example Wildlife blog you have made, so that when I click on the name of the tag in the navbar or in the tag selector in the blog page, it should go to a separate page which only displays the posts that has the selected tag.
I do not understand why it is not working for me since everything but the design is the same.
Thank you for creating this great project and I would greatly appreciate your support to fix this.

**Comment by arshad** [comment] 2020-08-17 16:59
Do you see any errors when you click on the tag in the navbar? Is it a page not found?

**Comment by JonathanPeterRajan** [comment] 2020-08-17 17:54
Thank you for your reply
There are no errors. The page only has the name of the tag as a header and that's it.
An example is the second picture in the original post of this thread.

**Comment by arshad** [comment] 2020-08-17 18:02
Hmm it looks like the either tags are not being created or not posts not associated with tags. Can you check if there are `PostTag` nodes in GraphQL?

1. With `gatsby develop` running, open `http://localhost:8000/___graphql`
2. Paste the following query and press run.

```js
query MyQuery {
  allPostTag {
    nodes {
      name
    }
  }
}
```

Do you see the tags returned? You should see something like this:

```json
{
  "data": {
    "allPostTag": {
      "nodes": [
        {
          "name": "Writing"
        },
        {
          "name": "Stories"
        }
      ]
    }
  }
}
```

**Comment by JonathanPeterRajan** [comment] 2020-08-17 18:07
Hi, the tags are being returned.
![image](https://user-images.githubusercontent.com/62900297/90429002-ca41ba00-e0bc-11ea-9753-c5786dc493e5.png)

**Comment by arshad** [comment] 2020-08-17 18:23
Can you run the following and see if `Post` are being linked to `PostTag`?

```js
query {
  allPost {
    group(field: tags___name) {
      fieldValue
      edges {
        node {
          title
        }
      }
    }
  }
}
```

**Comment by JonathanPeterRajan** [comment] 2020-08-17 18:27
{
  "data": {
    "allPost": {
      "group": [
        {
          "fieldValue": "Life",
          "edges": [
            {
              "node": {
                "title": "Title of the Post"
              }
            },
            {
              "node": {
                "title": "Title of the Post"
              }
            },
            {
              "node": {
                "title": "Title of the Post"
              }
            },
            {
              "node": {
                "title": "Tit"
              }
            },
            {
              "node": {
                "title": "Title of the Post"
              }
            },
            {
              "node": {
                "title": "Title of the Post"
              }
            },
            {
              "node": {
                "title": "Title of the Post"
              }
            }
          ]
        },
        {
          "fieldValue": "Technology",
          "edges": [
            {
              "node": {
                "title": "Title of the Post"
              }
            },
            {
              "node": {
                "title": "Title of the Post"
              }
            },
            {
              "node": {
                "title": "Title of the Post"
              }
            },
            {
              "node": {
                "title": "Tit"
              }
            },
            {
              "node": {
                "title": "Title of the Post"
              }
            },
            {
              "node": {
                "title": "Title of the Post"
              }
            },
            {
              "node": {
                "title": "Title of the Post"
              }
            }
          ]
        },
        {
          "fieldValue": "Writing",
          "edges": [
            {
              "node": {
                "title": "Title of the Post"
              }
            },
            {
              "node": {
                "title": "Title of the Post"
              }
            },
            {
              "node": {
                "title": "Title of the Post"
              }
            },
            {
              "node": {
                "title": "Tit"
              }
            },
            {
              "node": {
                "title": "Title of the Post"
              }
            },
            {
              "node": {
                "title": "Title of the Post"
              }
            },
            {
              "node": {
                "title": "Title of the Post"
              }
            }
          ]
        }
      ]
    }
  },
  "extensions": {}
}

**Comment by arshad** [comment] 2020-08-17 18:30
Yeah this looks good. Any errors in the console when you go to a tag page?

**Comment by JonathanPeterRajan** [comment] 2020-08-17 18:53
No errors. To test this, I added a tag called Test, to three of my existing posts and no problems occured.

**Comment by arshad** [comment] 2020-08-18 05:43
I'm going to take a look at the implementation again. So the new tag `Test` works but the others fail?

**Comment by JonathanPeterRajan** [comment] 2020-08-18 07:27
No, all the tags work, including the newly added Test tag, work.

**Comment by arshad** [comment] 2020-08-18 07:32
Nice. Ok to close this then?

**Comment by JonathanPeterRajan** [comment] 2020-08-18 07:36
So sorry for this misunderstanding. When I said they work, I meant to say that there aren't any problems in the console, refering to your previous message. 
My problem, that when you click on the tag button and goes to a new page which only contains posts from that tag, still persists.
Once again sorry for the unclear message.

**Comment by arshad** [comment] 2020-08-18 07:37
No worries. I'll take a look at it. Did you try a `gatsby clean` then `gatsby develop`? Does it make any difference?

**Comment by JonathanPeterRajan** [comment] 2020-08-18 07:40
Yes, I have tried many times and the problems is still there.

**Comment by JonathanPeterRajan** [comment] 2020-08-27 14:51
Any updates on this?

**Comment by arshad** [comment] 2020-08-28 05:47
@JonathanPeterRajan Can you help me reproduce this please?

**Comment by JonathanPeterRajan** [comment] 2020-08-28 10:19
I made a fresh build which provided the basics.
Then I added a blog using npm i @reflexjs/gatsby-theme-post
Then I used`https://github.com/reflexjs/reflex/issues/29#issuecomment-668211141` to make the tags selector for the blog page.
Then I added some test posts, which have different tags

This is the result

> ![Screenshot_2020-08-04 Reflex Reflex](https://user-images.githubusercontent.com/62900297/89286065-77421e80-d649-11ea-8bbc-d757c7aec384.png)
> ![Screenshot_2020-08-04 Reflex Reflex(1)](https://user-images.githubusercontent.com/62900297/89286069-790be200-d649-11ea-9253-28b17a8499e9.png)
> As shown from the images, after you click on a tag, it directs you to another page. In that none of the posts with that tag are showing.

**Comment by arshad** [comment] 2020-10-27 11:49
Closing this since lack of activity. Feel free to reopen if still an issue. Thank you.

**Closed by arshad** 2020-10-27 11:49 UTC
Labels: bug
