### ISSUE TITLE
Submenu on mobile

### ISSUE THREAD

**Issue by benbehringer** [reflexjs/reflex#83] opened 2020-09-17 09:51 UTC
Hi,

Thanks for the great project!

I have the following menu:
```
- Title
    - <Block src="FirstItem" />
    - <Block src="SecondItem" />
```

On desktop it works great, since I just need to hover "Title" to open the submenu. Yet, on mobile it should be possible to tap "Title" to open the submenu (if there is no link). It's not very accessible if nothing happens when tapping (and I don't want to create a page with just 2 items).

Is there an easy way to achieve this?

Thanks
Ben

**Comment by arshad** [comment] 2020-09-17 10:42
You should be able to achieve this using a `trigger` prop on the `NavMenu`.

1. Find `NavMenu` component in `content/blocks/header.mdx`. (Note: there are two `NavMenu` components. Find the one for mobile - most probably the second one).
2. Add the following prop to it `<NavMenu name={navName} gap={[0, 8]} borderTopWidth="1px" trigger="tap" />`

This should do it. This way you can keep the hover trigger on desktop and use tap on mobile.

**Comment by benbehringer** [comment] 2020-09-17 10:46
That was easy and works like a charm! Thank you so much!

**Comment by arshad** [comment] 2020-09-17 10:50
Happy it worked.

Tip: Instead of having multiple `<Block />` in your nav, you can use one `Block` and then embed multiple blocks inside. This would make it easier to theme/control the wrapper.

Example:

```md
// content/navs/header.mdx
- [Home](/)
- [Page](/basic)
- [Blog](/blog)
- Title
  - <Block src="submenu-block" />
```

Then in `content/blocks/submenu-block`

```
<Div p="4">
  <Block src="first-item" />
  <Block src="second-item" />
</Div>
```

**Comment by benbehringer** [comment] 2020-09-18 08:01
Great tip! Thanks!

**Comment by benbehringer** [comment] 2020-09-18 08:21
Still trying to understand NavMenu (now in the footer). Is there some documentation for options?

I have such a menu
```
- Title
    - [Link1](/link1/)
    - [Link2](/link2/)
```
and I build it in the footer as follows
```
   <NavMenu
            name="footer-menu"
            dropdown={false}
            my="6|0"
            gap="4|10|18"
          />
`
``

As a result, "Title" appears as a link without any destination. Yet, "Title" shouldn't be a link (since it's confusing and bad UX). Any easy way to fix this?

Thanks so much!
Ben

**Comment by arshad** [comment] 2020-09-18 08:53
@benbehringer hmm I can't reproduce this one. It's showing as a span for me (it does have a hover effect that makes it look like an `a` tag though).

For now the best place to look is the source code. https://github.com/reflexjs/reflex/blob/master/packages/gatsby-theme-nav/src/nav-menu.js#L179

Agree this needs better documentation (we're working on it).

**Comment by benbehringer** [comment] 2020-09-18 09:01
Here's a demo:

![2020-09-18 10 55 33](https://user-images.githubusercontent.com/37022575/93578727-f5f6df00-f99d-11ea-9fcf-06977a21c2d6.gif)

I don't want the span to have a hover effect, since it is quite confusing. In fact, I recorded multiple sessions where people tried to click the span and then left the page (likely because of the frustrating UX).

**Comment by arshad** [comment] 2020-09-18 09:03
Agreed. This is a bug. I'll create an issue and a fix.

**Comment by benbehringer** [comment] 2020-09-18 09:04
Great! Thanks!

**Comment by arshad** [comment] 2020-09-18 10:11
I pushed a fix for it and tagged a new release. You can upgrade: `yarn upgrade @reflexjs/gatsby-theme-base`.

**Comment by arshad** [comment] 2020-09-18 17:02
The easiest way right now is to use style props for `NavMenu` and the `sx` props to target child elements.

```js
<NavMenu
  gap="0|8"
  mr="null|10"
  sx={{
    color: "black",
    "a:hover, a[aria-current=page]": {
      color: "black",
      fontWeight: "semibold",
    },
  }}
/>
```

You can also shadow `src/@reflexjs/gatsby-theme-nav/nav-menu.js`, copy the content and add your style props to `NavMenuLink`, `NavMenuItem`..etc.

We are working on abstracting this a bit better so that it is easier to use style props on all elements.

**Comment by benbehringer** [comment] 2020-09-18 19:08
Awesome! Keep up the good work! Thanks!

**Comment by arshad** [comment] 2020-09-21 11:39
Closing this issue as fixed.

**Closed by arshad** 2020-09-21 11:39 UTC
